### ISSUE TITLE
Add example instructions for Keycloak configuration

### ISSUE THREAD

**Issue by Scrumplex** [ccrockett/omniauth-keycloak#14]
I am currently trying to get this to work with a fresh Keycloak, and am struggling the the Keycloak configuration.

I suspect I am missing something.

It would be nice to have an example configuration for Keycloak

**Comment by Scrumplex** [comment]
I am always getting this error from Keycloak: `{"error":"invalid_grant","error_description":"Incorrect redirect_uri"}`

I even configured redirect_uri to * (for testing purposes)

**Comment by Scrumplex** [comment]
Following request/response captured by Wireshark:

Request
```
POST /auth/realms/<myrealm>/protocol/openid-connect/token HTTP/1.1
User-Agent: Faraday v1.4.2
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Accept: */*
Host: 10.10.10.10:8080
Content-Length: 303

client_id=homepage&client_secret=<mysecret>&code=4146ecea-a066-4233-a44f-2195c059f03b.9141dd3b-c2b6-456a-ae87-f953d3db646b.ad9ec401-7646-451b-939b-e89feb23b5ff&grant_type=authorization_code&redirect_uri=http%3A%2F%2F10.10.10.10%3A3000%2Fusers%2Fauth%2Fkeycloakopenid%2Fcallback
```
Response
```
HTTP/1.1 400 Bad Request
Cache-Control: no-store
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Referrer-Policy: no-referrer
Date: Thu, 10 Jun 2021 10:32:32 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Content-Type: application/json
Content-Length: 70

{"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
```

**Comment by bplubell** [comment]
I have been having the same problem. I think the cause is that Keycloak, per a StackOverflow answer (https://stackoverflow.com/a/48315818), checks whether the request phase callback URL and callback phase callback URL match. It is not, in my instance, a problem with the configuration of Keycloak's "Valid Redirect URIs" (which for reference is set to `http://example.com/*`).

You can compare the `callback_url` in the omniuth-oauth2 gem for the two phases at [`lib/omniauth/strategies/oauth2.rb#request_phase`](https://github.com/omniauth/omniauth-oauth2/blob/66520787187f692f90f630d932d23e44c5fee998/lib/omniauth/strategies/oauth2.rb#L58) and [`lib/omniauth/strategies/oauth2.rb#callback_phase`](https://github.com/omniauth/omniauth-oauth2/blob/66520787187f692f90f630d932d23e44c5fee998/lib/omniauth/strategies/oauth2.rb#L84) and note that, at least for me, the callback phase has additional query parameters ("session", "session_state", and "code"). This stems from the callback_phase using the [`build_access_token` method](https://github.com/omniauth/omniauth-oauth2/blob/66520787187f692f90f630d932d23e44c5fee998/lib/omniauth/strategies/oauth2.rb#L124) which adds additional query parameters (`token_params`).

For troubleshooting, I changed the `build_access_token` as shown below and authentication started working.

```rb
def build_access_token
  verifier = request.params["code"]
  client.auth_code.get_token(verifier,
    {:redirect_uri => callback_url},
    deep_symbolize(options.auth_token_params))
end
```

I am not certain 1) why this gem's implementation of `build_access_method` calls `.gsub` (omniauth-oauth2 gem uses `callback_url` without modification) or 2) what use the `token_params` have in the `redirect_uri` (authentication works without them).

**Comment by bplubell** [comment]
In a new Rails project, I no longer get this error when using the current [`build_access_token`](https://github.com/ccrockett/omniauth-keycloak/blob/68136923dcde022cd81d6c9ad41d2715afdb8cde/lib/omniauth/strategies/keycloak-openid.rb#L82) method. There are a lot of configuration differences with the other app I was working with and I'm not real sure which is responsible for making one work and the other not.

**Comment by ccrockett** [comment]
as @bplubell pointed out keycloak's implementation of oauth returns extra query params to the callback url ("session", "session_state", and "code"). Unfortunately this breaks the omniauth-oauth2 gems validation of the `redirect_uri`, my gem tries to "fix" that by removing the query params from the redirect_uri (that's the `gsub` in the `build_access_token` method). There are a lot of configuration options on the Keycloak side and so this could very well be breaking things under certain conditions/configurations.

Setting up Keycloak is beyond the scope of this project and would require more time than I have to keep up to date. With that said, I was able to setup a fresh installation of keycloak using [their instructions](https://www.keycloak.org/getting-started/getting-started-docker). 
**The only difference when setting my instance up was I set the root url to `http://localhost:3000` under the 'Secure your first app' section** (instead of `https://www.keycloak.org/app/`)

With a new Rails 7 project:
`Gemfile:`
```
....

gem 'omniauth-keycloak', '~> 1.4'
gem 'omniauth-rails_csrf_protection', '~> 1.0', '>= 1.0.1'
```

`config/initializers/omniauth.rb:`
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :keycloak_openid, 'myclient', '',
    client_options: {site: 'http://localhost:8080', realm: 'myrealm', base_url: ''},
    name: 'keycloak'
end
```

`app/views/logins/index.html.erb:`
```
<%= form_tag('/auth/keycloak', method: 'post', data: {turbo: false}) do %>
  <button type='submit'>Login with Keycloak</button>
<% end %>
```

I hope this helps.

**Comment by Scrumplex** [comment]
I have used saml2 in the last year. When I was looking at this again, I stumbled over the exact same issue.

The problem on my end was, that the first callback URL included a `?locale=` parameter. So when the oauth library wanted to fetch a token, it didn't include that same parameter.
This was caused by this in my application controller:
```ruby
  def default_url_options
    { locale: I18n.locale }
  end
```

So when the view inserted the URL for the authorization path (`user_keycloakopenid_omniauth_authorize_path`), it included this default parameter.
The fix for me was to set this locale parameter to `nil` in my `route.rb` like this:
```ruby
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, defaults: { locale: nil }
```

I hope this will be helpful for other people
